thecut/news/urls.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, unicode_literals
from . import feeds, views
from django.conf.urls import include, url


urls = [

    url(r'^$',
        views.ListView.as_view(), name='article_list'),
    url(r'^(?P<page>\d+)$',
        views.ListView.as_view(), name='article_list'),
    url(r'^(?P<slug>[\w-]+)/$',
        views.ListView.as_view(), name='article_list'),
    url(r'^(?P<slug>[\w-]+)/(?P<page>\d+)$',
        views.ListView.as_view(), name='article_list'),

    url(r'^latest\.xml$',
        feeds.LatestArticleFeed(), name='article_feed'),
    url(r'^(?P<slug>[\w-]+)/latest\.xml$',
        feeds.LatestCategoryArticleFeed(), name='article_feed'),

    url(r'^(?P<year>\d{4})/(?P<month>\d{2})/(?P<day>\d{2})/(?P<slug>[\w-]+)$',
        views.DetailView.as_view(), name='article_detail'),

    # These old url names are kept for backwards-compatibility
    url(r'^(?P<page>\d+)$',
        views.ListView.as_view(), name='paginated_article_list'),
    url(r'^(?P<slug>[\w-]+)/$',
        views.ListView.as_view(), name='category_article_list'),
    url(r'^(?P<slug>[\w-]+)/(?P<page>\d+)$',
        views.ListView.as_view(), name='paginated_category_article_list'),
    url(r'^(?P<slug>[\w-]+)/latest\.xml$',
        feeds.LatestCategoryArticleFeed(), name='category_article_feed'),

]

urlpatterns = [
    url(r'^', include(urls, namespace='news')),
]

thecut/news/models.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, unicode_literals
from django.conf import settings
from django.db import models
from django.utils import timezone
from thecut.publishing.models import Content, SiteContent
from thecut.publishing.utils import generate_unique_slug

try:
    from django.urls import reverse
except ImportError:
    from django.core.urlresolvers import reverse


class AbstractArticle(SiteContent):
    """Generic article."""

    slug = models.SlugField(unique_for_date='publish_at')

    summary = models.TextField(default='', blank=True)

    class Meta(SiteContent.Meta):
        abstract = True
        ordering = ['-publish_at']
        unique_together = ['site', 'publish_at', 'slug']

    def get_next(self):
        queryset = self.__class__.objects.exclude(pk=self.pk).filter(
            site=self.site, publish_at__gte=self.publish_at).active().order_by(
            'publish_at')[:1]
        return queryset[0] if queryset else None

    def get_previous(self):
        queryset = self.__class__.objects.exclude(pk=self.pk).filter(
            site=self.site, publish_at__lte=self.publish_at).active().order_by(
            '-publish_at')[:1]
        return queryset[0] if queryset else None

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = generate_unique_slug(
                self.title,
                self.__class__.objects.filter(
                    site=self.site,
                    publish_at__year=self.publish_at.year,
                    publish_at__month=self.publish_at.month,
                    publish_at__day=self.publish_at.day))
        return super(AbstractArticle, self).save(*args, **kwargs)


class AbstractArticleCategory(Content):

    slug = models.SlugField(unique=True)

    class Meta(Content.Meta):
        abstract = True
        verbose_name_plural = 'article categories'

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = generate_unique_slug(self.title,
                                             self.__class__.objects.all())
        super(AbstractArticleCategory, self).save(*args, **kwargs)


class Article(AbstractArticle):

    categories = models.ManyToManyField('news.ArticleCategory',
                                        related_name='articles', blank=True)

    def get_absolute_url(self):
        # Ensure consistent urls are determined from the server's timezone.

        server_timezone = timezone.pytz.timezone(settings.TIME_ZONE)

        if timezone.is_naive(self.publish_at):
            publish_at = server_timezone.localize(self.publish_at)
        else:
            publish_at = server_timezone.normalize(self.publish_at)

        return reverse('news:article_detail',
                       kwargs={'year': '%04d' % (publish_at.year),
                               'month': '%02d' % (publish_at.month),
                               'day': '%02d' % (publish_at.day),
                               'slug': self.slug})


class ArticleCategory(AbstractArticleCategory):

    def get_absolute_url(self):
        return reverse('news:article_list', kwargs={'slug': self.slug})

thecut/news/views.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, unicode_literals
from . import settings
from .models import Article, ArticleCategory
from django.shortcuts import get_object_or_404, redirect
from django.views import generic


class DetailView(generic.DateDetailView):

    allow_future = True

    context_object_name = 'article'

    date_field = 'publish_at'

    model = Article

    month_format = '%m'

    template_name_field = 'template'

    def get_queryset(self, *args, **kwargs):
        queryset = super(DetailView, self).get_queryset(*args, **kwargs)
        return queryset.current_site().active()


class ListView(generic.ListView):

    allow_empty = settings.ALLOW_EMPTY_ARTICLE_LIST

    context_object_name = 'article_list'

    model = Article

    category_model = ArticleCategory

    paginate_by = settings.ARTICLES_PAGINATE_BY

    def get(self, *args, **kwargs):
        page = self.kwargs.get('page', None)
        if page is not None and int(page) < 2:
            category = self.get_category()
            if category:
                return redirect('news:article_list', slug=category.slug,
                                permanent=True)
            else:
                return redirect('news:article_list', permanent=True)
        return super(ListView, self).get(*args, **kwargs)

    def get_category(self):
        if not hasattr(self, '_category'):
            slug = self.kwargs.get('slug', None)
            if slug is not None:
                category = get_object_or_404(
                    self.category_model.objects.active(), slug=slug)
            else:
                category = None
            self._category = category
        return self._category

    def get_context_data(self, *args, **kwargs):
        context_data = super(ListView, self).get_context_data(*args, **kwargs)
        category = self.get_category()
        context_data.setdefault('category', category)
        return context_data

    def get_queryset(self, *args, **kwargs):
        queryset = super(ListView, self).get_queryset(*args, **kwargs)
        category = self.get_category()
        if category:
            queryset = queryset.filter(categories=category)
        return queryset.current_site().active()

    def get_template_names(self, *args, **kwargs):
        template_names = super(ListView, self).get_template_names(*args,
                                                                  **kwargs)
        category = self.get_category()
        if category and category.template:
            template_names = [category.template] + template_names
        return template_names

thecut/news/templates/base.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
  
  <head>
    <title>{% block title %}{% endblock %}</title>
    {% block extrahead %}{% endblock %}
  </head>
  
  <body>
    {% block content %}
    {% endblock %}
  </body>
  
</html>

thecut/news/templates/news/article_detail.html
{% extends "news/base.html" %}


{% block title %}{{ article.title }} - {{ block.super }}{% endblock %}


{% block extrahead %}
  {{ block.super }}
  {% if article and not article.is_indexable %}<meta name="robots" content="noindex" />{% endif %}
  {% if article.meta_description %}<meta name="description" content="{{ article.meta_description }}" />{% endif %}
{% endblock %}


{% block content %}

  <h1>{{ article.heading }}</h1>
  <h2>{{ article.publish_at|date:"l jS F Y" }}</h2>

  {% if article.featured_content %}<div>{{ article.featured_content }}</div>{% endif %}
  {% if article.content %}<div>{{ article.content|safe }}</div>{% endif %}

{% endblock %}

thecut/news/templates/news/article_list.html
{% extends "news/base.html" %}


{% block title %}{{ category|default:"Articles" }} - {{ block.super }}{% endblock %}


{% block extrahead %}
  {{ block.super }}

  {% if category %}
    {% if category and not category.is_indexable %}<meta name="robots" content="noindex" />{% endif %}
    {% if category.meta_description %}<meta name="description" content="{{ category.meta_description }}" />{% endif %}
    <link rel="alternate" href="{% url "news:article_feed" category.slug %}" type="application/atom+xml" title="Latest {{ category }}" />
  {% else %}
    <link rel="alternate" href="{% url "news:article_feed" %}" type="application/atom+xml" title="Latest news articles" />
  {% endif %}

  {% if page_obj.paginator.num_pages > 1 %}{% spaceless %}
    {% if page_obj.has_previous %}
      {% if category %}
        <link rel="prev" href="{% if page_obj.previous_page_number == 1 %}{% url "news:article_list" slug=category.slug %}{% else %}{% url "news:article_list" slug=category.slug page=page_obj.previous_page_number %}{% endif %}" />
      {% else %}
        <link rel="prev" href="{% if page_obj.previous_page_number == 1 %}{% url "news:article_list" %}{% else %}{% url "news:article_list" page=page_obj.previous_page_number %}{% endif %}" />
      {% endif %}
    {% endif %}
    {% if page_obj.has_next %}
      {% if category %}
        <link rel="next" href="{% url "news:article_list" slug=category.slug page=page_obj.next_page_number %}" />
      {% else %}
        <link rel="next" href="{% url "news:article_list" page=page_obj.next_page_number %}" />
      {% endif %}
    {% endif %}
  {% endspaceless %}{% endif %}
{% endblock %}


{% block content %}
  <h1>{{ category|default:"News" }}</h1>
  {% if category.featured_content %}<div>{{ category.featured_content }}</div>{% endif %}
  {% if category.content %}<div>{{ category.content|safe }}</div>{% endif %}

  {% for article in article_list %}
  {% if forloop.first %}<ul>{% endif %}
  <li>
    <a href="{{ article.get_absolute_url }}">
      {{ article.publish_at }}
      {{ article }}
      {{ article.summary }}
    </a>
  </li>
  {% if forloop.last %}</ul>{% endif %}
  {% empty %}
    <p>No news to display.</p>
  {% endfor %}

  {% if page_obj.paginator.num_pages > 1 %}
  <div>
    Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.

    {% if page_obj.has_previous %}
      {% if category %}
        <a href="{% if page_obj.previous_page_number == 1 %}{% url "news:article_list" slug=category.slug %}{% else %}{% url "news:article_list" slug=category.slug page=page_obj.previous_page_number %}{% endif %}" rel="previous">previous</a>
      {% else %}
        <a href="{% if page_obj.previous_page_number == 1 %}{% url "news:article_list" %}{% else %}{% url "news:article_list" page=page_obj.previous_page_number %}{% endif %}" rel="previous">previous</a>
      {% endif %}
    {% endif %}

    {% if page_obj.has_next %}
      {% if category %}
        <a href="{% url "news:article_list" slug=category.slug page=page_obj.next_page_number %}" rel="next">next</a>
      {% else %}
        <a href="{% url "news:article_list" page=page_obj.next_page_number %}" rel="next">next</a>
      {% endif %}
    {% endif %}

  </div>
  {% endif %}

{% endblock %}

thecut/news/templates/news/base.html
{% extends "base.html" %}